09-11 10:47:43 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "SELECT TOP ?  FROM "; expected "identifier"; SQL statement:
select top ?  from [42001-169]
09-11 10:48:05 jdbc[5]: exception
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "SELECT TOP ?  FROM "; expected "identifier"; SQL statement:
select top ?  from [42001-169]
09-11 10:49:34 jdbc[8]: exception
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "SELECT  FROM LIMIT[*] ? "; expected "identifier"; SQL statement:
select  from limit ? [42001-169]
09-11 11:18:38 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: No data is available [2000-169]
09-11 11:19:05 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: No data is available [2000-169]
09-11 11:19:21 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: No data is available [2000-169]
09-12 09:58:14 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "TIPOPARTICIPANTE"; expected "TRUNCATE, {"; SQL statement:
TIPOPARTICIPANTE [42001-169]
09-12 10:01:31 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Column count does not match; SQL statement:
insert into atributo values('hello','asd') [21002-169]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.message.DbException.get(DbException.java:135)
	at org.h2.command.dml.Insert.prepare(Insert.java:226)
	at org.h2.command.Parser.prepareCommand(Parser.java:218)
	at org.h2.engine.Session.prepareLocal(Session.java:415)
	at org.h2.engine.Session.prepareCommand(Session.java:364)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1114)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:164)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:152)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1311)
	at org.h2.server.web.WebApp.query(WebApp.java:1001)
	at org.h2.server.web.WebApp$1.next(WebApp.java:964)
	at org.h2.server.web.WebApp$1.next(WebApp.java:953)
	at org.h2.server.web.WebThread.process(WebThread.java:166)
	at org.h2.server.web.WebThread.run(WebThread.java:93)
	at java.lang.Thread.run(Unknown Source)
09-12 10:03:00 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Column "SEQUENCE_NAME" not found; SQL statement:
select sequence_name system_sequence_0aa73c94_f03c_4fe6_a994_4bf3b34d72c1 [42122-169]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.expression.ExpressionColumn.optimize(ExpressionColumn.java:138)
	at org.h2.expression.Alias.optimize(Alias.java:47)
	at org.h2.command.dml.Select.prepare(Select.java:799)
	at org.h2.command.Parser.prepareCommand(Parser.java:218)
	at org.h2.engine.Session.prepareLocal(Session.java:415)
	at org.h2.engine.Session.prepareCommand(Session.java:364)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1114)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:164)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:152)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1311)
	at org.h2.server.web.WebApp.query(WebApp.java:1001)
	at org.h2.server.web.WebApp$1.next(WebApp.java:964)
	at org.h2.server.web.WebApp$1.next(WebApp.java:953)
	at org.h2.server.web.WebThread.process(WebThread.java:166)
	at org.h2.server.web.WebThread.run(WebThread.java:93)
	at java.lang.Thread.run(Unknown Source)
09-12 10:03:05 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Column "SYSTEM_SEQUENCE_0AA73C94_F03C_4FE6_A994_4BF3B34D72C1" not found; SQL statement:
select system_sequence_0aa73c94_f03c_4fe6_a994_4bf3b34d72c1 [42122-169]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.expression.ExpressionColumn.optimize(ExpressionColumn.java:138)
	at org.h2.command.dml.Select.prepare(Select.java:799)
	at org.h2.command.Parser.prepareCommand(Parser.java:218)
	at org.h2.engine.Session.prepareLocal(Session.java:415)
	at org.h2.engine.Session.prepareCommand(Session.java:364)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1114)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:164)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:152)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1311)
	at org.h2.server.web.WebApp.query(WebApp.java:1001)
	at org.h2.server.web.WebApp$1.next(WebApp.java:964)
	at org.h2.server.web.WebApp$1.next(WebApp.java:953)
	at org.h2.server.web.WebThread.process(WebThread.java:166)
	at org.h2.server.web.WebThread.run(WebThread.java:93)
	at java.lang.Thread.run(Unknown Source)
09-12 10:11:18 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Column "NEXTVAL.IDSITUACAOEMISSOR" not found; SQL statement:
SELECT nextval.idsituacaoemissor [42122-169]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.expression.ExpressionColumn.optimize(ExpressionColumn.java:138)
	at org.h2.command.dml.Select.prepare(Select.java:799)
	at org.h2.command.Parser.prepareCommand(Parser.java:218)
	at org.h2.engine.Session.prepareLocal(Session.java:415)
	at org.h2.engine.Session.prepareCommand(Session.java:364)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1114)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:164)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:152)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1311)
	at org.h2.server.web.WebApp.query(WebApp.java:1001)
	at org.h2.server.web.WebApp$1.next(WebApp.java:964)
	at org.h2.server.web.WebApp$1.next(WebApp.java:953)
	at org.h2.server.web.WebThread.process(WebThread.java:166)
	at org.h2.server.web.WebThread.run(WebThread.java:93)
	at java.lang.Thread.run(Unknown Source)
09-12 10:11:39 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Column "SYSTEM_SEQUENCE_0AA73C94_F03C_4FE6_A994_4BF3B34D72C1" not found; SQL statement:
SELECT nextval(system_sequence_0aa73c94_f03c_4fe6_a994_4bf3b34d72c1) [42122-169]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.expression.ExpressionColumn.optimize(ExpressionColumn.java:138)
	at org.h2.expression.Function.optimize(Function.java:1746)
	at org.h2.command.dml.Select.prepare(Select.java:799)
	at org.h2.command.Parser.prepareCommand(Parser.java:218)
	at org.h2.engine.Session.prepareLocal(Session.java:415)
	at org.h2.engine.Session.prepareCommand(Session.java:364)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1114)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:164)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:152)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1311)
	at org.h2.server.web.WebApp.query(WebApp.java:1001)
	at org.h2.server.web.WebApp$1.next(WebApp.java:964)
	at org.h2.server.web.WebApp$1.next(WebApp.java:953)
	at org.h2.server.web.WebThread.process(WebThread.java:166)
	at org.h2.server.web.WebThread.run(WebThread.java:93)
	at java.lang.Thread.run(Unknown Source)
09-12 10:11:54 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Column "IDATRIBUTO" not found; SQL statement:
SELECT nextval(idatributo) [42122-169]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.expression.ExpressionColumn.optimize(ExpressionColumn.java:138)
	at org.h2.expression.Function.optimize(Function.java:1746)
	at org.h2.command.dml.Select.prepare(Select.java:799)
	at org.h2.command.Parser.prepareCommand(Parser.java:218)
	at org.h2.engine.Session.prepareLocal(Session.java:415)
	at org.h2.engine.Session.prepareCommand(Session.java:364)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1114)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:164)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:152)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1311)
	at org.h2.server.web.WebApp.query(WebApp.java:1001)
	at org.h2.server.web.WebApp$1.next(WebApp.java:964)
	at org.h2.server.web.WebApp$1.next(WebApp.java:953)
	at org.h2.server.web.WebThread.process(WebThread.java:166)
	at org.h2.server.web.WebThread.run(WebThread.java:93)
	at java.lang.Thread.run(Unknown Source)
09-12 10:12:34 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Sequence "IDTIPOPARTICIPANTE" not found; SQL statement:
SELECT nextval('idtipoparticipante') [90036-169]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.schema.Schema.getSequence(Schema.java:474)
	at org.h2.expression.Function.getSequence(Function.java:1287)
	at org.h2.expression.Function.getValueWithArgs(Function.java:1135)
	at org.h2.expression.Function.getValue(Function.java:447)
	at org.h2.command.dml.Select.queryFlat(Select.java:519)
	at org.h2.command.dml.Select.queryWithoutCache(Select.java:618)
	at org.h2.command.dml.Query.query(Query.java:307)
	at org.h2.command.dml.Query.query(Query.java:277)
	at org.h2.command.dml.Query.query(Query.java:36)
	at org.h2.command.CommandContainer.query(CommandContainer.java:86)
	at org.h2.command.Command.executeQuery(Command.java:191)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:173)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:152)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1311)
	at org.h2.server.web.WebApp.query(WebApp.java:1001)
	at org.h2.server.web.WebApp$1.next(WebApp.java:964)
	at org.h2.server.web.WebApp$1.next(WebApp.java:953)
	at org.h2.server.web.WebThread.process(WebThread.java:166)
	at org.h2.server.web.WebThread.run(WebThread.java:93)
	at java.lang.Thread.run(Unknown Source)
09-12 10:15:48 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Sequence "SYSTEM_SEQUENCE_0AA73C94_F03C_4FE6_A994_4BF3B34D72C1" belongs to a table; SQL statement:
DROP SEQUENCE system_sequence_0aa73c94_f03c_4fe6_a994_4bf3b34d72c1 [90082-169]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.command.ddl.DropSequence.update(DropSequence.java:49)
	at org.h2.command.CommandContainer.update(CommandContainer.java:75)
	at org.h2.command.Command.executeUpdate(Command.java:230)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:177)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:152)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1311)
	at org.h2.server.web.WebApp.query(WebApp.java:1001)
	at org.h2.server.web.WebApp$1.next(WebApp.java:964)
	at org.h2.server.web.WebApp$1.next(WebApp.java:953)
	at org.h2.server.web.WebThread.process(WebThread.java:166)
	at org.h2.server.web.WebThread.run(WebThread.java:93)
	at java.lang.Thread.run(Unknown Source)
09-12 10:17:51 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "ALTER SEQUENCE SYSTEM_SEQUENCE_0AA73C94_F03C_4FE6_A994_4BF3B34D72C1 RENAME[*] TO AS "; SQL statement:
AltER seqUENCE system_sequence_0aa73c94_f03c_4fe6_a994_4bf3b34d72c1 rename to as [42000-169]
09-12 10:21:47 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "ALTER SEQUENCE SYSTEM_SEQUENCE_0AA73C94_F03C_4FE6_A994_4BF3B34D72C1 RENAME[*] TO AS "; SQL statement:
ALTER SEQUENCE system_sequence_0aa73c94_f03c_4fe6_a994_4bf3b34d72c1 RENAME TO as [42000-169]
09-12 10:22:46 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Sequence "SYSTEM_SEQUENCE_0AA73C94_F03C_4FE6_A994_4BF3B34D72C1" belongs to a table; SQL statement:
drop SEQUENCE system_sequence_0aa73c94_f03c_4fe6_a994_4bf3b34d72c1 [90082-169]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.command.ddl.DropSequence.update(DropSequence.java:49)
	at org.h2.command.CommandContainer.update(CommandContainer.java:75)
	at org.h2.command.Command.executeUpdate(Command.java:230)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:177)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:152)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1311)
	at org.h2.server.web.WebApp.query(WebApp.java:1001)
	at org.h2.server.web.WebApp$1.next(WebApp.java:964)
	at org.h2.server.web.WebApp$1.next(WebApp.java:953)
	at org.h2.server.web.WebThread.process(WebThread.java:166)
	at org.h2.server.web.WebThread.run(WebThread.java:93)
	at java.lang.Thread.run(Unknown Source)
09-12 10:24:16 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "INFORMATION_SCHEMA[*].SEQUENCES"; expected "INSERT, {"; SQL statement:
INFORMATION_SCHEMA.SEQUENCES [42001-169]
09-12 10:25:46 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Table "ATRIBUTO" not found; SQL statement:
drop table atributo [42102-169]
09-12 10:25:46 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Table "ATRIBUTO" not found; SQL statement:
drop table atributo [42102-169]
09-12 10:25:46 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Table "ATRIBUTO" not found; SQL statement:
drop table atributo [42102-169]
09-12 10:25:46 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Table "ATRIBUTO" not found; SQL statement:
drop table atributo [42102-169]
09-12 10:25:46 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Table "ATRIBUTO" not found; SQL statement:
drop table atributo [42102-169]
09-12 10:26:15 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Table "ATRIBUTO" not found; SQL statement:
drop table atributo [42102-169]
09-12 10:26:15 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Table "ATRIBUTO" not found; SQL statement:
drop table atributo [42102-169]
09-12 13:20:36 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "ALTER TABLE EMPRESA RENAME SETOR[*] TO DESCRICAOATIVIDADE "; expected "TO"; SQL statement:
alter table empresa rename setor to descricaoatividade [42001-169]
09-12 13:21:18 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "ALTER TABLE EMPRESA RENAME 'setor'[*] TO 'descricaoatividade' "; expected "TO"; SQL statement:
alter table empresa rename 'setor' to 'descricaoatividade' [42001-169]
09-12 13:22:36 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "ALTER TABLE EMPRESA CHANGE[*] SETOR DESCRICAOATIVIDADE VARCHAR(500) "; expected "., ADD, SET, RENAME, DROP, ALTER"; SQL statement:
alter table empresa change setor descricaoatividade varchar(500) [42001-169]
09-12 13:23:08 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "ALTER TABLE EMPRESA RENAME ""setor""[*] TO ""descricaoatividade"" "; expected "TO"; SQL statement:
alter table empresa rename "setor" to "descricaoatividade" [42001-169]
09-12 13:24:38 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "alter table empresa rename column setor to descricaoatividade[*]"";"; SQL statement:
alter table empresa rename column setor to descricaoatividade"; [42000-169]
09-12 13:24:43 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "ALTER TABLE EMPRESA RENAME COLUMN[*] SETOR TO DESCRICAOATIVIDADE "; expected "TO"; SQL statement:
alter table empresa rename column setor to descricaoatividade [42001-169]
09-12 13:27:26 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "ALTER TABLE EMPRESA CHANGE[*] SETOR DESCRICAOATIVIDADE VARCHAR(500) "; expected "., ADD, SET, RENAME, DROP, ALTER"; SQL statement:
alter table empresa change setor descricaoatividade varchar(500) [42001-169]
09-12 13:28:45 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Table "ATRIBUTO" not found; SQL statement:
drop table atributo [42102-169]
09-12 13:28:45 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Table "ATRIBUTO" not found; SQL statement:
drop table atributo [42102-169]
09-12 13:28:45 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Table "ATRIBUTO" not found; SQL statement:
drop table atributo [42102-169]
09-12 13:28:45 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Table "ATRIBUTO" not found; SQL statement:
drop table atributo [42102-169]
09-12 13:28:45 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Table "ATRIBUTO" not found; SQL statement:
drop table atributo [42102-169]
09-12 13:28:45 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Table "ATRIBUTO" not found; SQL statement:
drop table atributo [42102-169]
09-12 13:28:45 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Table "ATRIBUTO" not found; SQL statement:
drop table atributo [42102-169]
09-12 13:28:45 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Table "ATRIBUTO" not found; SQL statement:
drop table atributo [42102-169]
09-12 13:28:45 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Table "ATRIBUTO" not found; SQL statement:
drop table atributo [42102-169]
09-12 13:28:45 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Table "ATRIBUTO" not found; SQL statement:
drop table atributo [42102-169]
09-12 13:28:45 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Table "ATRIBUTO" not found; SQL statement:
drop table atributo [42102-169]
09-12 13:28:45 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Table "ATRIBUTO" not found; SQL statement:
drop table atributo [42102-169]
09-12 13:28:45 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Table "ATRIBUTO" not found; SQL statement:
drop table atributo [42102-169]
09-12 13:28:45 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Table "ATRIBUTO" not found; SQL statement:
drop table atributo [42102-169]
09-12 13:28:45 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Table "ATRIBUTO" not found; SQL statement:
drop table atributo [42102-169]
09-12 13:28:45 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Table "ATRIBUTO" not found; SQL statement:
drop table atributo [42102-169]
09-12 13:29:53 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Table "IDCATEGORIAREGCVM" not found; SQL statement:
drop table idcategoriaregcvm [42102-169]
09-12 13:29:53 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Table "IDEMPRESA" not found; SQL statement:
drop table idempresa [42102-169]
09-12 13:29:53 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Table "IDPAIS" not found; SQL statement:
drop table idpais [42102-169]
09-12 13:29:53 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Table "IDRELATORIOANUAL" not found; SQL statement:
drop table idrelatorioanual [42102-169]
09-12 13:29:53 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Table "IDSITUACAOEMISSOR" not found; SQL statement:
drop table idsituacaoemissor [42102-169]
09-12 13:29:53 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Table "IDSITUACAOREGCVM" not found; SQL statement:
drop table idsituacaoregcvm [42102-169]
09-12 13:29:53 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Table "IDTIPOPARTICIPANTE" not found; SQL statement:
drop table idtipoparticipante [42102-169]
09-12 13:30:28 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Sequence "IDCATEGORIAREGCVM" not found; SQL statement:
drop sequence idcategoriaregcvm [90036-169]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.command.ddl.DropSequence.update(DropSequence.java:45)
	at org.h2.command.CommandContainer.update(CommandContainer.java:75)
	at org.h2.command.Command.executeUpdate(Command.java:230)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:177)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:152)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1311)
	at org.h2.server.web.WebApp.query(WebApp.java:1001)
	at org.h2.server.web.WebApp$1.next(WebApp.java:964)
	at org.h2.server.web.WebApp$1.next(WebApp.java:953)
	at org.h2.server.web.WebThread.process(WebThread.java:166)
	at org.h2.server.web.WebThread.run(WebThread.java:93)
	at java.lang.Thread.run(Unknown Source)
09-12 13:30:28 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Sequence "IDEMPRESA" not found; SQL statement:
drop sequence idempresa [90036-169]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.command.ddl.DropSequence.update(DropSequence.java:45)
	at org.h2.command.CommandContainer.update(CommandContainer.java:75)
	at org.h2.command.Command.executeUpdate(Command.java:230)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:177)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:152)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1311)
	at org.h2.server.web.WebApp.query(WebApp.java:1001)
	at org.h2.server.web.WebApp$1.next(WebApp.java:964)
	at org.h2.server.web.WebApp$1.next(WebApp.java:953)
	at org.h2.server.web.WebThread.process(WebThread.java:166)
	at org.h2.server.web.WebThread.run(WebThread.java:93)
	at java.lang.Thread.run(Unknown Source)
09-12 13:30:28 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Sequence "IDPAIS" not found; SQL statement:
drop sequence idpais [90036-169]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.command.ddl.DropSequence.update(DropSequence.java:45)
	at org.h2.command.CommandContainer.update(CommandContainer.java:75)
	at org.h2.command.Command.executeUpdate(Command.java:230)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:177)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:152)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1311)
	at org.h2.server.web.WebApp.query(WebApp.java:1001)
	at org.h2.server.web.WebApp$1.next(WebApp.java:964)
	at org.h2.server.web.WebApp$1.next(WebApp.java:953)
	at org.h2.server.web.WebThread.process(WebThread.java:166)
	at org.h2.server.web.WebThread.run(WebThread.java:93)
	at java.lang.Thread.run(Unknown Source)
09-12 13:30:28 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Sequence "IDRELATORIOANUAL" not found; SQL statement:
drop sequence idrelatorioanual [90036-169]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.command.ddl.DropSequence.update(DropSequence.java:45)
	at org.h2.command.CommandContainer.update(CommandContainer.java:75)
	at org.h2.command.Command.executeUpdate(Command.java:230)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:177)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:152)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1311)
	at org.h2.server.web.WebApp.query(WebApp.java:1001)
	at org.h2.server.web.WebApp$1.next(WebApp.java:964)
	at org.h2.server.web.WebApp$1.next(WebApp.java:953)
	at org.h2.server.web.WebThread.process(WebThread.java:166)
	at org.h2.server.web.WebThread.run(WebThread.java:93)
	at java.lang.Thread.run(Unknown Source)
09-12 13:30:28 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Sequence "IDSITUACAOEMISSOR" not found; SQL statement:
drop sequence idsituacaoemissor [90036-169]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.command.ddl.DropSequence.update(DropSequence.java:45)
	at org.h2.command.CommandContainer.update(CommandContainer.java:75)
	at org.h2.command.Command.executeUpdate(Command.java:230)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:177)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:152)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1311)
	at org.h2.server.web.WebApp.query(WebApp.java:1001)
	at org.h2.server.web.WebApp$1.next(WebApp.java:964)
	at org.h2.server.web.WebApp$1.next(WebApp.java:953)
	at org.h2.server.web.WebThread.process(WebThread.java:166)
	at org.h2.server.web.WebThread.run(WebThread.java:93)
	at java.lang.Thread.run(Unknown Source)
09-12 13:30:29 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Sequence "IDSITUACAOREGCVM" not found; SQL statement:
drop sequence idsituacaoregcvm [90036-169]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.command.ddl.DropSequence.update(DropSequence.java:45)
	at org.h2.command.CommandContainer.update(CommandContainer.java:75)
	at org.h2.command.Command.executeUpdate(Command.java:230)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:177)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:152)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1311)
	at org.h2.server.web.WebApp.query(WebApp.java:1001)
	at org.h2.server.web.WebApp$1.next(WebApp.java:964)
	at org.h2.server.web.WebApp$1.next(WebApp.java:953)
	at org.h2.server.web.WebThread.process(WebThread.java:166)
	at org.h2.server.web.WebThread.run(WebThread.java:93)
	at java.lang.Thread.run(Unknown Source)
09-12 13:30:29 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Sequence "IDTIPOPARTICIPANTE" not found; SQL statement:
drop sequence idtipoparticipante [90036-169]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.command.ddl.DropSequence.update(DropSequence.java:45)
	at org.h2.command.CommandContainer.update(CommandContainer.java:75)
	at org.h2.command.Command.executeUpdate(Command.java:230)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:177)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:152)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1311)
	at org.h2.server.web.WebApp.query(WebApp.java:1001)
	at org.h2.server.web.WebApp$1.next(WebApp.java:964)
	at org.h2.server.web.WebApp$1.next(WebApp.java:953)
	at org.h2.server.web.WebThread.process(WebThread.java:166)
	at org.h2.server.web.WebThread.run(WebThread.java:93)
	at java.lang.Thread.run(Unknown Source)
09-12 14:37:08 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: No data is available [2000-169]
09-12 14:37:38 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: No data is available [2000-169]
09-12 14:43:45 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: No data is available [2000-169]
